name: Build C++

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build project
        run: |
          sudo apt-get update
          sudo apt-get install -y -f build-essential g++ cmake
          g++ GameDie.cpp -Wall -Werror 
